/* Canonical error codes shared by backend (thrown) and frontend (matched).
 * Stable string values — the frontend may branch on these. */
export enum ExtErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  ENCRYPTION_KEY_INVALID = 'ENCRYPTION_KEY_INVALID',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  WHM_UNREACHABLE = 'WHM_UNREACHABLE',
  WHM_AUTH_FAILED = 'WHM_AUTH_FAILED',
  WHM_API_ERROR = 'WHM_API_ERROR',
  CPANEL_API_ERROR = 'CPANEL_API_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  INTERNAL = 'INTERNAL',
}
